# Generated by Django 3.2.15 on 2023-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20220920_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_atencion',
            field=models.IntegerField(default=True),
        ),
    ]
