# Generated by Django 3.2.15 on 2023-03-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
