# Generated by Django 3.2 on 2024-01-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apanel', '0003_auto_20230403_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
